apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-dep
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: aicareeracr.azurecr.io/assignment:v3
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: entrypoint
            mountPath: /entrypoint.sh
      volumes:
        - name: entrypoint
          secret:
            secretName: cart-entrypoint		   
      imagePullSecrets:
      - name: regcred

